/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolingRouteImport } from './routes/tooling'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheatSheetRouteImport } from './routes/cheat-sheet'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsVirtualRouteImport } from './routes/products/virtual'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as ProductsDbRouteImport } from './routes/products/db'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ProductsProductIdEditRouteImport } from './routes/products/$productId/edit'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products/$productId'

const ToolingRoute = ToolingRouteImport.update({
  id: '/tooling',
  path: '/tooling',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetRoute = CheatSheetRouteImport.update({
  id: '/cheat-sheet',
  path: '/cheat-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVirtualRoute = ProductsVirtualRouteImport.update({
  id: '/products/virtual',
  path: '/products/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDbRoute = ProductsDbRouteImport.update({
  id: '/products/db',
  path: '/products/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsProductIdRoute,
} as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ApiProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/dashboard': typeof DashboardRoute
  '/tooling': typeof ToolingRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteWithChildren
  '/products/db': typeof ProductsDbRoute
  '/products/new': typeof ProductsNewRoute
  '/products/virtual': typeof ProductsVirtualRoute
  '/products/': typeof ProductsIndexRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/dashboard': typeof DashboardRoute
  '/tooling': typeof ToolingRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteWithChildren
  '/products/db': typeof ProductsDbRoute
  '/products/new': typeof ProductsNewRoute
  '/products/virtual': typeof ProductsVirtualRoute
  '/products': typeof ProductsIndexRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/dashboard': typeof DashboardRoute
  '/tooling': typeof ToolingRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRouteWithChildren
  '/products/db': typeof ProductsDbRoute
  '/products/new': typeof ProductsNewRoute
  '/products/virtual': typeof ProductsVirtualRoute
  '/products/': typeof ProductsIndexRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/cheat-sheet'
    | '/dashboard'
    | '/tooling'
    | '/api/products'
    | '/products/$productId'
    | '/products/db'
    | '/products/new'
    | '/products/virtual'
    | '/products/'
    | '/api/products/$productId'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/cheat-sheet'
    | '/dashboard'
    | '/tooling'
    | '/api/products'
    | '/products/$productId'
    | '/products/db'
    | '/products/new'
    | '/products/virtual'
    | '/products'
    | '/api/products/$productId'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/categories'
    | '/cheat-sheet'
    | '/dashboard'
    | '/tooling'
    | '/api/products'
    | '/products/$productId'
    | '/products/db'
    | '/products/new'
    | '/products/virtual'
    | '/products/'
    | '/api/products/$productId'
    | '/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  CheatSheetRoute: typeof CheatSheetRoute
  DashboardRoute: typeof DashboardRoute
  ToolingRoute: typeof ToolingRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRouteWithChildren
  ProductsDbRoute: typeof ProductsDbRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsVirtualRoute: typeof ProductsVirtualRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tooling': {
      id: '/tooling'
      path: '/tooling'
      fullPath: '/tooling'
      preLoaderRoute: typeof ToolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheet': {
      id: '/cheat-sheet'
      path: '/cheat-sheet'
      fullPath: '/cheat-sheet'
      preLoaderRoute: typeof CheatSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/virtual': {
      id: '/products/virtual'
      path: '/products/virtual'
      fullPath: '/products/virtual'
      preLoaderRoute: typeof ProductsVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/db': {
      id: '/products/db'
      path: '/products/db'
      fullPath: '/products/db'
      preLoaderRoute: typeof ProductsDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof ProductsProductIdRoute
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

interface ProductsProductIdRouteChildren {
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
}

const ProductsProductIdRouteChildren: ProductsProductIdRouteChildren = {
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
}

const ProductsProductIdRouteWithChildren =
  ProductsProductIdRoute._addFileChildren(ProductsProductIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  CheatSheetRoute: CheatSheetRoute,
  DashboardRoute: DashboardRoute,
  ToolingRoute: ToolingRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRouteWithChildren,
  ProductsDbRoute: ProductsDbRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsVirtualRoute: ProductsVirtualRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
